// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"github.com/LyricTian/gin-admin/v10/internal/mods"
	"github.com/LyricTian/gin-admin/v10/internal/mods/agent"
	"github.com/LyricTian/gin-admin/v10/internal/mods/agent/api"
	"github.com/LyricTian/gin-admin/v10/internal/mods/agent/biz"
	"github.com/LyricTian/gin-admin/v10/internal/mods/agent/dal"
	"github.com/LyricTian/gin-admin/v10/internal/mods/agent/llm"
	"github.com/LyricTian/gin-admin/v10/internal/mods/agent/retrieval"
	"github.com/LyricTian/gin-admin/v10/internal/mods/shop"
	api2 "github.com/LyricTian/gin-admin/v10/internal/mods/shop/api"
	biz2 "github.com/LyricTian/gin-admin/v10/internal/mods/shop/biz"
	dal2 "github.com/LyricTian/gin-admin/v10/internal/mods/shop/dal"
	"github.com/LyricTian/gin-admin/v10/internal/mods/shop/jd"
	"github.com/LyricTian/gin-admin/v10/internal/mods/shop/notify"
	"github.com/LyricTian/gin-admin/v10/pkg/util"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	store := &dal.Store{
		DB: db,
	}
	trans := &util.Trans{
		DB: db,
	}
	kimi := llm.NewKimi()
	cache := retrieval.NewCache()
	eventHub := biz.NewEventHub()
	service := biz.NewService(store, trans, kimi, cache, eventHub)
	apiAPI := &api.API{
		Service: service,
	}
	agentAgent := &agent.Agent{
		DB:      db,
		API:     apiAPI,
		Service: service,
	}
	status := biz2.NewStatus()
	apiStatus := &api2.Status{
		StatusBIZ: status,
	}
	dalStore := &dal2.Store{
		DB: db,
	}
	client := jd.NewChromeClient()
	notifier := notify.NewServerChan()
	bizService := biz2.NewService(dalStore, client, notifier, trans)
	management := &api2.Management{
		Service: bizService,
	}
	scheduler := shop.NewScheduler(bizService)
	shopShop := &shop.Shop{
		DB:            db,
		StatusAPI:     apiStatus,
		ManagementAPI: management,
		Scheduler:     scheduler,
	}
	modsMods := &mods.Mods{
		Agent: agentAgent,
		Shop:  shopShop,
	}
	injector := &Injector{
		DB: db,
		M:  modsMods,
	}
	return injector, func() {
		cleanup()
	}, nil
}
