// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"github.com/LyricTian/gin-admin/v10/internal/mods"
	"github.com/LyricTian/gin-admin/v10/internal/mods/shop"
	"github.com/LyricTian/gin-admin/v10/internal/mods/shop/api"
	"github.com/LyricTian/gin-admin/v10/internal/mods/shop/biz"
	"github.com/LyricTian/gin-admin/v10/internal/mods/shop/dal"
	"github.com/LyricTian/gin-admin/v10/internal/mods/shop/jd"
	"github.com/LyricTian/gin-admin/v10/internal/mods/shop/notify"
	"github.com/LyricTian/gin-admin/v10/pkg/util"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	status := biz.NewStatus()
	apiStatus := &api.Status{
		StatusBIZ: status,
	}
	store := &dal.Store{
		DB: db,
	}
	client := jd.NewChromeClient()
	notifier := notify.NewServerChan()
	trans := &util.Trans{
		DB: db,
	}
	service := biz.NewService(store, client, notifier, trans)
	management := &api.Management{
		Service: service,
	}
	scheduler := shop.NewScheduler(service)
	shopShop := &shop.Shop{
		DB:            db,
		StatusAPI:     apiStatus,
		ManagementAPI: management,
		Scheduler:     scheduler,
	}
	modsMods := &mods.Mods{
		Shop: shopShop,
	}
	injector := &Injector{
		DB: db,
		M:  modsMods,
	}
	return injector, func() {
		cleanup()
	}, nil
}
